kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
    volume.kubernetes.io/storage-provisioner: vpc.block.csi.ibm.io
  resourceVersion: '155125'
  name: system-storage
  namespace: openshift-operators
  ownerReferences:
    - apiVersion: apps.3scale.net/v1alpha1
      kind: APIManager
      name: apimanager-sample
      uid: 602126d4-bd07-4cdb-97e3-741a8c866ae3
      controller: true
      blockOwnerDeletion: true
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: 3scale-api-management
    threescale_component: system
    threescale_component_element: app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
